language: csharp
solution: Discord Game Chooser.sln
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
  
#deploy:
#  provider: releases
#  api_key:
#    secure: $API_KEY
#  file:
#    - "Discord Game Chooser.exe"
#    - "Discord Game Chooser.exe.config"
#    - "Discord Game Chooser.pdb"
#  skip_cleanup: true
#  on:
#    tags: false
